### ISSUE TITLE
Не указаны минимальные требования для работы

### ISSUE THREAD

**Issue by Yuego** [futurecolors/django-geoip#21]
Нигде не увидел, что для работы приложения нужны django-appconf и progressbar
Не указано, какую минимальную величину должен иметь параметр mysql 'max_allowed_packet'

Добавьте пожалуйста в документацию.

**Comment by coagulant** [comment]
Зависимости указаны в setup.py, надо ли их повторять в документации. Мне кажется это не имеет смысла. 

А какой max_allowed_packet нужен?

**Comment by Yuego** [comment]
В setup.py заглянуть не догадался.

С дефолтным max_allowed_packet у меня приложение падало с ошибкой (с какой, уже не упомню). Помогло увеличение оного параметра до 16М.

**Comment by coagulant** [comment]
Ок, добавлю строчку про это в доки.
