### ISSUE TITLE
"too many SQL variables" из-за bulk_create

### ISSUE THREAD

**Issue by marselester** [futurecolors/django-geoip#23]
sqlite3 `too many SQL variables` при выполнение `./manage.py geoip_update`.
Проблема возникает из-за использования `bulk_create`:
https://github.com/futurecolors/django-geoip/blob/dev/django_geoip/management/ipgeobase.py#L137

**Comment by coagulant** [comment]
Это не бага билиотеки, починено в django 1.5 trunk, поэтому wontfix.
