### ISSUE TITLE
lat / lng перепутаны или я запутался в координатной системе?

### ISSUE THREAD

**Issue by max107** [futurecolors/django-geoip#37]
После geoip_update в базе данных видим следующие значения для Кирова:

```
latitude 49.662659
longitude 58.596081
```

Далее идем в http://itouchmap.com/latlong.html ставим точку по этим координатам http://d.pr/i/HLpP и получаем Казахстан.

Меняем местами значения у latitude и longitude и получаем Киров.
http://d.pr/i/xpJ

Что я делаю не правильно или что я не знаю о координатных системах? Пожалуйста подскажите.

**Comment by coagulant** [comment]
Исправил, теперь широта и долгота на своих местах.
При обновлении БД из ipgeobase старые координаты останутся, их можно поменять вручную.
Если привязок нет, то проще удалить всю географию и запустить синхронизацию начисто.

**Comment by max107** [comment]
Боюсь спрашивать как с этой батарейкой работали люди, раз никто ранее не задавался вопросом почему координаты перепутаны.

Спасибо за исправление.

**Comment by max107** [comment]
@coagulant оформите пожалуйста новую версию в pypi. Баг серьезный.

**Comment by coagulant** [comment]
Баг чинится без обновления прописыванием в settings.py

```
IPGEOBASE_CITIES_FIELDS = ['city_id', 'city_name', 'region_name', 'district_name', 'latitude', 'longitude']
```

Можете проверить?

**Comment by max107** [comment]
Проверил. Теперь все на своих местах. Спасибо.

И тем не менее, я считаю, что лучше выкатить мелкий ап, чтобы никто в перспективе не тратил свое время в пустую на поиск столь глупого бага.
